import "@packages/ui/globals.css";
import "./globals.css";

import { FaviconIco, FaviconPng, FaviconSvg } from "@packages/assets";
import { cn } from "@packages/ui/lib/utils";
import type { Metadata } from "next";

import { fontVariables } from "@/app/fonts";
import { ThemeProvider } from "@/app/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cookies } from "next/headers";

import { defaultAppCachedCatalogs } from "@/app/cached-catalogs";

import { Header } from "./header";

const getData = async () => {
  const data = await defaultAppCachedCatalogs.landpadsCachedQuery.getData();

  return {
    data,
  };
};

export default async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { data } = await getData();

  const cook = await cookies();
  const auth = cook.get("auth")?.value === "true";

  console.log("Cached landpads:", data?.landpads?.length);
  console.log("auth cookie:", auth); // Log the value of the "theme" cookie

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href={FaviconIco.src} sizes="32x32" />
        <link rel="icon" href={FaviconSvg.src} type="image/svg+xml" />
        <link rel="apple-touch-icon" href={FaviconPng.src} />
      </head>

      <body
        className={cn(
          "text-foreground group/body overscroll-none font-sans antialiased [--footer-height:calc(var(--spacing)*14)] [--header-height:calc(var(--spacing)*14)] xl:[--footer-height:calc(var(--spacing)*24)]",
          fontVariables,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <Header auth={auth} />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
};
