schema: ./packages/graphql/autogen/schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    default:
      url: https://spacex-production.up.railway.app/graphql
      headers:
        Authorization
