import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

const renogareRegularFont = localFont({
  src: "../public/fonts/Renogare-Regular.otf",
  variable: "--font-renogare-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={renogareRegularFont.className}>{children}</body>
    </html>
  );
}
