import crypto from "crypto";
import fs from "fs/promises";
import path from "path";

import { logger } from "./logger";

export const NEXT_JS_ASSETS_FOLDER = "assets";

export const SOURCE_ASSETS_DIR = "public";

export const NEXT_JS_APPS = ["apps/docs"];

const nextJsProjectsPaths = NEXT_JS_APPS.map((app) =>
  path.resolve(__dirname, "../../..", app),
);

// Source directory for assets
const sourceAssetsDir = path.resolve(__dirname, "..", SOURCE_ASSETS_DIR);

// Function to generate a hash from file content
const generateFileHash = (content: Buffer): string => {
  return crypto.createHash("sha256").update(content).digest("hex").slice(0, 12);
};
const resetNextJsProjectAssetsFolder = async (projectPath: string) => {
  const assetsDir = path.join(projectPath, "public", NEXT_JS_ASSETS_FOLDER);

  try {
    // Try reading the directory
    const files = await fs.readdir(assetsDir);

    if (files.length > 0) {
      logger.info(
        `Deleting ${files.length} asset${files.length === 1 ? "" : "s"} in: ${assetsDir}`,
      );
    }

    // Delete all files in the directory
    await Promise.all(
      files.map((file) => fs.unlink(path.join(assetsDir, file))),
    );
  } catch (err: any) {
    // If the directory doesn't exist, create it
    if (err.code === "ENOENT") {
      logger.info(`Creating assets directory: ${assetsDir}`);
      await fs.mkdir(assetsDir, { recursive: true });
    } else {
      throw err;
    }
  }
};

const processFile = async (file: string, projects: string[]) => {
  logger.info(`Processing file: ${file}`);
  const sourcePath = path.join(sourceAssetsDir, file);

  const fileContent = await fs.readFile(sourcePath);

  const fileHash = generateFileHash(fileContent);
  const fileExtension = path.extname(file);
  const hashedFilename = `${fileHash}${fileExtension}`;

  await Promise.all(
    projects.map(async (project) => {
      const targetAssetsDir = path.join(project, "public/assets");
      const targetPath = path.join(targetAssetsDir, hashedFilename);
      await fs.writeFile(targetPath, fileContent);
    }),
  );

  const varName = file
    .replace(fileExtension, "")
    .replace(/-/g, "_")
    .toUpperCase();

  return `  ${varName}: "/assets/${hashedFilename}",\n`;
};

(async () => {
  logger.info("Starting next-js-assets sync process...");

  // Reset all Next.js project assets folders
  await Promise.all(
    nextJsProjectsPaths.map((projectPath) =>
      resetNextJsProjectAssetsFolder(projectPath),
    ),
  );

  // Read all files from the source assets directory
  const files = await fs.readdir(sourceAssetsDir);

  let indexFileContent =
    "// This file is auto-generated by next-js-assets. Do not edit manually.\n\n";
  indexFileContent += "export const assets = {\n";

  const processedFiles = await Promise.all(
    files.map((file) => processFile(file, nextJsProjectsPaths)),
  );

  indexFileContent += processedFiles.join("");
  indexFileContent += "};\n";

  const indexFilePath = path.resolve(__dirname, "..", "src/assets-autogen.ts");
  await fs.writeFile(indexFilePath, indexFileContent);

  logger.info("Next-js-assets sync process completed successfully.");
})();
