name: cd

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  prepare:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'release' && contains(github.event.release.name, 'default-app'))
    runs-on: ubuntu-latest
    outputs: # expose step outputs as job outputs
      semver: ${{ steps.calc.outputs.semver }}
      short_sha: ${{ steps.calc.outputs.short_sha }}
      tag: ${{ github.event.release.tag_name || github.event.release.name || '' }}
    steps:
      - name: calculate-variables
        id: calc
        shell: bash
        env:
          # Prefer the tag name for release events; fall back to release.name.
          # For non-release events this will be empty, which is fine.
          TAG: ${{ github.event.release.tag_name || github.event.release.name || '' }}
        run: |
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            # If it's a release, derive semver from TAG or ref_name
            RAW_TAG="${TAG:-${{ github.ref_name }}}"
            SEMVER="${RAW_TAG##*-}"  # after last '-'
            SEMVER="${SEMVER#v}"    # drop leading 'v'
          fi

          echo "semver=$SEMVER" >> "$GITHUB_OUTPUT"
          echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Show values
        run: |
          echo "Semver: ${{ steps.calc.outputs.semver }}"
          echo "Short SHA: ${{ steps.calc.outputs.short_sha }}"

  build-and-push-default-app:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'release' && contains(github.event.release.name, 'default-app'))
    needs: [prepare]
    uses: ./.github/workflows/build-and-push.yml
    with:
      dockerfile_path: apps/default-app/Dockerfile
      image_name: ${{ vars.DOCKER_DEFAULT_APP_IMAGE_NAME }}
      semver: ${{ needs.prepare.outputs.semver }}
      short_sha: ${{ needs.prepare.outputs.short_sha }}
    secrets: inherit

  promote-to-staging-default-app:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'release' && contains(github.event.release.name, 'default-app'))
    needs: [prepare, build-and-push-default-app]
    uses: ./.github/workflows/promote.yml
    with:
      environment: staging
      image_name: ${{ vars.DOCKER_DEFAULT_APP_IMAGE_NAME }}
      short_sha: ${{ needs.prepare.outputs.short_sha }}
    secrets: inherit

  promote-to-prod-default-app:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'release' && contains(github.event.release.name, 'default-app'))
    needs: [prepare, promote-to-staging-default-app]
    uses: ./.github/workflows/promote.yml
    with:
      environment: prod
      image_name: ${{ vars.DOCKER_DEFAULT_APP_IMAGE_NAME }}
      short_sha: ${{ needs.prepare.outputs.short_sha }}
    secrets: inherit
