name: cd

on:
  release:
    types: [published]

env:
  TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event.release.tag_name || github.sha }}

  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs: # expose step outputs as job outputs
      raw_tag: ${{ steps.calc.outputs.raw_tag }}
      name: ${{ steps.calc.outputs.name }}
      version: ${{ steps.calc.outputs.version }}
      short_sha: ${{ steps.calc.outputs.short_sha }}
    steps:
      - id: calc
        shell: bash
        run: |
          RAW_TAG="${TAG}"
          NAME="${RAW_TAG%-*}"               # before last '-'
          VERSION="${RAW_TAG##*-}"           # after last '-'
          VERSION="${VERSION#v}"             # drop leading 'v'
          SHORT_SHA="${GITHUB_SHA::7}"
          {
            echo "raw_tag=$RAW_TAG"
            echo "name=$NAME"
            echo "version=$VERSION"
            echo "short_sha=$SHORT_SHA"
          } >> "$GITHUB_OUTPUT"

  default-app-build-and-push-staging:
    if: contains(github.event.release.name, 'default-app')
    needs: prepare
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for Azure OIDC login

    env: # make them envs in this job
      RAW_TAG: ${{ needs.prepare.outputs.raw_tag }}
      NAME: ${{ needs.prepare.outputs.name }}
      VERSION: ${{ needs.prepare.outputs.version }}
      SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}
      SENTRY_RELEASE: ${{ needs.prepare.outputs.raw_tag }}

    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: azure-login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: acr-login
        run: az acr login --name "${{ vars.ACR_NAME }}"

      - name: install-node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          check-latest: true
          cache: "yarn"

      - name: install-yarn
        # Install the same version as the main package.json
        run: npm i -g yarn@1.22.22

      - name: restore-turbo-cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock', 'turbo.json', '**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: install-dependencies
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: Build and Push
        run: |
          docker buildx build \
            --file apps/default-app/Dockerfile \
            --tag "${{ vars.ACR_LOGIN_SERVER }}/${{ vars.DOCKER_IMAGE_NAME }}:$VERSION" \
            --tag "${{ vars.ACR_LOGIN_SERVER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ vars.DOCKER_IMAGE_TAG }}" \
            --tag "${{ vars.ACR_LOGIN_SERVER }}/${{ vars.DOCKER_IMAGE_NAME }}:$SHORT_SHA" \
            --push \
            .

      - name: sentry-deployment
        uses: getsentry/action-release@v1
        with:
          environment: staging

  promote-to-prod:
    if: contains(github.event.release.name, 'default-app')
    needs: default-app-build-and-push-staging
    environment: production
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.version }}
      SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}

    steps:
      - name: azure-login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: acr-login
        run: az acr login --name "${{ vars.ACR_NAME }}"

      - name: retag-and-push
        run: |
          skopeo copy \
            --src-tls-verify=false \
            --dest-tls-verify=false \
            docker://"${{ vars.ACR_LOGIN_SERVER }}/${{ vars.DOCKER_IMAGE_NAME }}:$VERSION" \
            docker://"${{ vars.ACR_LOGIN_SERVER }}/${{ vars.DOCKER_IMAGE_NAME }}:prod"
